"""End-to-end pipeline runner against /data/clean_data/.

Runs all episodes through Stage A (Robometer) → DemInf scoring → cohort
accumulation → Stage B (DemInf lookup) → decision, using a store adapter
that reads directly from /data/clean_data/ without copying any files.

Usage:
    cd /data/reward_model
    /data/robometer/.venv/bin/python3 -u scripts/run_local_pipeline.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# --- make rdf importable without installing ---
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

os.environ.setdefault("RDF_STORAGE", "local")

import time
import uuid
from datetime import datetime, timezone

import yaml

from rdf.decision.decide import decide_all
from rdf.harness.catalog import LocalCatalog
from rdf.harness.config import get_models_config, get_paths_config, get_pipeline_config
from rdf.harness.queue import LocalQueue
from rdf.harness.storage import ObjectStore
from rdf.schemas.models import CatalogRow, CohortMessage, EpisodeManifest
from rdf.stage_a_robometer.worker import run_worker as run_stage_a
from rdf.stage_a_robometer.worker import stream_episodes
from rdf.stage_b_deminf.infer_worker import run_infer_worker as run_stage_b

_paths = get_paths_config()
_pipeline = get_pipeline_config()
_models = get_models_config()

CLEAN_DATA = Path(_paths.clean_data_dir)
SCRATCH = Path(_paths.scratch_dir)
SCRATCH.mkdir(parents=True, exist_ok=True)

DEMINF_DATA = Path(_paths.deminf_data_dir)
_OPENX_PYTHON = _paths.openx_python
_DEMINF_SCORE_SCRIPT = Path(__file__).parent / "deminf_score_episodes.py"


def _setup_deminf_data(manifests: list) -> int:
    """Symlink any missing episodes into DEMINF_DATA/{task_id}/train/ for scoring.

    Each episode dir gets symlinks to its MCAP and MP4 files from clean_data.
    The cached .npz is generated by deminf_score_episodes.py on first run.
    Returns the number of newly linked episodes.
    """
    added = 0
    for m in manifests:
        train_dir = DEMINF_DATA / m.task_id / "train"
        train_dir.mkdir(parents=True, exist_ok=True)
        ep_src = CLEAN_DATA / m.episode_id
        ep_dst = train_dir / m.episode_id
        if ep_dst.exists():
            continue
        ep_dst.mkdir()
        for fname in [
            "cam_head.mp4",
            "cam_wrist.mp4",
            f"{m.episode_id}.mcap",
            "metadata.yaml",
        ]:
            src = ep_src / fname
            if src.exists():
                (ep_dst / fname).symlink_to(src)
        added += 1
    return added


def _get_checkpoint_for_task(task_id: str) -> str | None:
    """Return the best checkpoint path for task_id, or None if none exist.

    Prefers the configured deminf_train_steps checkpoint; falls back to the
    highest available step if that exact step hasn't been saved yet.
    """
    task_ckpt_dir = Path(_paths.deminf_ckpts_dir) / task_id
    if not task_ckpt_dir.exists():
        return None
    exact = sorted(task_ckpt_dir.glob(f"*/{_models.deminf_train_steps}"))
    if exact:
        return str(exact[-1])
    all_steps = sorted(
        task_ckpt_dir.glob("*/[0-9]*"),
        key=lambda p: int(p.name),
    )
    return str(all_steps[-1]) if all_steps else None


def _setup_training_data(task_id: str, pass_episode_ids: list[str]) -> None:
    """Create train_sel/ and test_sel/ under DEMINF_DATA/{task_id} for VAE training.

    Symlinks up to deminf_train_episodes Stage-A-pass episodes into train_sel/.
    Uses the first 5 of those as the validation split (test_sel/).
    """
    selected = pass_episode_ids[: _models.deminf_train_episodes]
    task_data = DEMINF_DATA / task_id
    for split_name, eps in [("train_sel", selected), ("test_sel", selected[:5])]:
        split_dir = task_data / split_name
        split_dir.mkdir(exist_ok=True)
        for ep_id in eps:
            src = task_data / "train" / ep_id
            dst = split_dir / ep_id
            if src.exists() and not dst.exists():
                dst.symlink_to(src)


def _preprocess_deminf_data(task_id: str, splits: list[str]) -> None:
    """Generate _cached.npz files for the given splits before training.

    Runs preprocess_episodes.py in the openx conda env so the training
    dataloader never has to parse raw MCAP files.  Idempotent — already-cached
    episodes are skipped.
    """
    import subprocess

    preprocess_script = Path(_paths.deminf_root) / "scripts" / "preprocess_episodes.py"
    task_data = DEMINF_DATA / task_id
    proc = subprocess.run(
        [
            _OPENX_PYTHON,
            str(preprocess_script),
            f"--root={task_data}",
            "--splits", *splits,
            f"--workers={_models.video_preprocess_workers}",
        ],
        cwd=_paths.deminf_root,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"DemInf preprocessing failed for task_id={task_id!r} splits={splits}"
            f" (exit {proc.returncode})"
        )


def _train_deminf_for_task(task_id: str, pass_episode_ids: list[str]) -> str:
    """Train a DemInf VAE for task_id and return the checkpoint path.

    Steps:
      1. Create train_sel/ and test_sel/ symlinks (subset of pass episodes).
      2. Preprocess those episodes to _cached.npz so training loads instantly.
      3. Run scripts/train.py in the openx conda env.

    Saves checkpoints to deminf_ckpts_dir/{task_id}/clean_data_vae/ every
    deminf_train_save_freq steps; total steps = deminf_train_steps.
    """
    import subprocess

    output_dir = Path(_paths.deminf_ckpts_dir) / task_id
    output_dir.mkdir(parents=True, exist_ok=True)
    _setup_training_data(task_id, pass_episode_ids)
    _preprocess_deminf_data(task_id, splits=["train_sel", "test_sel"])

    train_script = Path(_paths.deminf_root) / "scripts" / "train.py"
    config_path = Path(__file__).parent.parent / "configs" / "quality" / "clean_data_vae.py"

    env = os.environ.copy()
    env["RDF_DEMINF_DATA"] = str(DEMINF_DATA / task_id)

    proc = subprocess.run(
        [
            _OPENX_PYTHON,
            str(train_script),
            f"--config={config_path}:sa",
            f"--path={output_dir}",
            "--name=clean_data_vae",
            "--include_timestamp=False",
            f"--config.steps={_models.deminf_train_steps}",
            f"--config.save_freq={_models.deminf_train_save_freq}",
            "--config.dataloader.datasets.clean_data.train_split=train_sel",
            "--config.dataloader.datasets.clean_data.val_split=test_sel",
        ],
        cwd=_paths.deminf_root,
        env=env,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"DemInf VAE training failed for task_id={task_id!r} (exit {proc.returncode})"
        )

    ckpt = _get_checkpoint_for_task(task_id)
    if not ckpt:
        raise RuntimeError(f"Checkpoint not found after training for task_id={task_id!r}")
    return ckpt


def _run_deminf_scoring(manifests: list, ckpts_by_task: dict[str, str]) -> None:
    """Run deminf_score_episodes.py once per task_id using the given checkpoints.

    Each run gets RDF_DEMINF_DATA → DEMINF_DATA/{task_id} and RDF_DEMINF_CKPT →
    the resolved checkpoint for that task.  Per-task scores are merged into the
    single shared scores file at paths_config.deminf_scores_file.
    """
    import json
    import subprocess
    import tempfile
    from collections import defaultdict

    by_task: dict[str, list] = defaultdict(list)
    for m in manifests:
        by_task[m.task_id].append(m)

    all_scores: dict[str, float] = {}
    last_ckpt = ""

    for task_id in sorted(by_task):
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp_scores = f.name
        env = os.environ.copy()
        env["RDF_DEMINF_DATA"] = str(DEMINF_DATA / task_id)
        env["RDF_DEMINF_CKPT"] = ckpts_by_task[task_id]
        env["RDF_DEMINF_SCORES"] = tmp_scores
        proc = subprocess.run(
            [_OPENX_PYTHON, str(_DEMINF_SCORE_SCRIPT)],
            cwd=_paths.deminf_root,
            env=env,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"DemInf scoring failed for task_id={task_id!r} (exit {proc.returncode})"
            )
        with open(tmp_scores) as f:
            data = json.load(f)
        all_scores.update(data.get("scores", {}))
        last_ckpt = data.get("ckpt", last_ckpt)
        os.unlink(tmp_scores)

    scores_out = Path(_paths.deminf_scores_file)
    scores_out.parent.mkdir(parents=True, exist_ok=True)
    scores_out.write_text(
        json.dumps(
            {"scores": all_scores, "split": _models.deminf_split, "ckpt": last_ckpt},
            indent=2,
        )
    )


class CleanDataStore(ObjectStore):
    """Read-only adapter: maps pipeline key conventions to /data/clean_data/ layout.

    Key conventions expected by the pipeline:
      raw/{episode_id}/head.mp4   ← cam_head.mp4
      raw/{episode_id}/data.mcap  ← {episode_id}.mcap
      raw/{episode_id}/metadata.yaml
    """

    def _resolve(self, key: str) -> Path | None:
        parts = key.split("/")
        if len(parts) < 3 or parts[0] != "raw":
            return None
        episode_id = parts[1]
        filename = parts[2]
        ep_dir = CLEAN_DATA / episode_id
        if filename == "head.mp4":
            return ep_dir / "cam_head.mp4"
        if filename == "data.mcap":
            # episode_XXXX.mcap
            matches = list(ep_dir.glob("*.mcap"))
            return matches[0] if matches else None
        if filename == "metadata.yaml":
            return ep_dir / "metadata.yaml"
        return None

    def get_bytes(self, key: str) -> bytes:
        p = self._resolve(key)
        if p is None or not p.exists():
            raise FileNotFoundError(key)
        return p.read_bytes()

    def exists(self, key: str) -> bool:
        p = self._resolve(key)
        return p is not None and p.exists()

    def put_bytes(self, key: str, data: bytes) -> None:
        # write to scratch for clean-bucket simulation
        dest = SCRATCH / key
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)

    def delete(self, key: str) -> None:
        p = SCRATCH / key
        if p.exists():
            p.unlink()

    def list_keys(self, prefix: str) -> list[str]:
        # Only enumerate raw/ prefix for known episodes
        if prefix.startswith("raw/"):
            parts = prefix.split("/")
            if len(parts) >= 2:
                ep_dir = CLEAN_DATA / parts[1]
                if ep_dir.exists():
                    return [
                        f"raw/{parts[1]}/head.mp4",
                        f"raw/{parts[1]}/data.mcap",
                        f"raw/{parts[1]}/metadata.yaml",
                    ]
        return []


def _parse_metadata(episode_id: str) -> dict:
    meta_path = CLEAN_DATA / episode_id / "metadata.yaml"
    meta = yaml.safe_load(meta_path.read_text())
    tasks = meta.get("tasks", [])
    task = tasks[0] if tasks else meta.get("task", "unknown")
    task_id = meta.get("task_id")
    if task_id is None:
        print(
            f"  WARNING: {episode_id}/metadata.yaml has no task_id field"
            f" — using default_task_id={_pipeline.default_task_id!r}",
            flush=True,
        )
        task_id = _pipeline.default_task_id
    return {
        "task": task,
        "task_id": task_id,
        "instruction": task,  # no instruction field in these files
        "embodiment": meta.get("robot_type", "unknown"),
        "robot_id": meta.get("robot_id", "unknown"),
    }


def build_manifests(instruction_override: str | None = None) -> list[EpisodeManifest]:
    manifests = []
    for ep_dir in sorted(CLEAN_DATA.iterdir()):
        if not ep_dir.is_dir():
            continue
        episode_id = ep_dir.name
        fields = _parse_metadata(episode_id)
        instruction = instruction_override or fields["instruction"]
        m = EpisodeManifest(
            episode_id=episode_id,
            s3_prefix=f"raw/{episode_id}/",
            robot_id=fields["robot_id"],
            embodiment=fields["embodiment"],
            task=fields["task"],
            task_id=fields["task_id"],
            instruction=instruction,
            head_video_key=f"raw/{episode_id}/head.mp4",
            mcap_key=f"raw/{episode_id}/data.mcap",
            metadata_key=f"raw/{episode_id}/metadata.yaml",
            created_at=datetime.now(timezone.utc),
        )
        manifests.append(m)
    return manifests


def main():
    t_start = time.monotonic()
    print(f"\n{'='*60}")
    print("RDF Pipeline — Local Integration Test")
    print(f"Data: {CLEAN_DATA}  Scratch: {SCRATCH}")
    print(f"{'='*60}\n")

    store = CleanDataStore()
    catalog = LocalCatalog(root=str(SCRATCH / "catalog"))
    episode_queue = LocalQueue("rdf-episodes", root=str(SCRATCH / "queues"))
    cohort_queue = LocalQueue("rdf-cohorts", root=str(SCRATCH / "queues"))

    robometer_threshold = _pipeline.robometer_threshold
    deminf_threshold = _pipeline.deminf_threshold

    # --- Ingestion: build manifests, seed catalog, enqueue ---
    print("[ Ingestion ]")
    instruction_override = os.environ.get("RDF_INSTRUCTION")
    if instruction_override:
        print(f"  Instruction override: {instruction_override!r}")
    manifests = build_manifests(instruction_override=instruction_override)
    print(f"  Found {len(manifests)} episodes")
    now = datetime.now(timezone.utc)
    for m in manifests:
        catalog.upsert_row(CatalogRow(
            episode_id=m.episode_id,
            task=m.task,
            embodiment=m.embodiment,
            robot_id=m.robot_id,
            pipeline_mode=_pipeline.mode,
            created_at=now,
            updated_at=now,
        ))
        episode_queue.enqueue(m.model_dump(mode="json"), dedup_id=m.episode_id)
    print(f"  Seeded catalog and enqueued {len(manifests)} episodes\n")

    # --- Stage A: Robometer scoring ---
    print("[ Stage A — Robometer ]")
    max_a = int(os.environ.get("RDF_MAX_EPISODES", len(manifests)))
    if max_a < len(manifests):
        print(f"  (smoke-test mode: processing {max_a}/{len(manifests)} episodes)")

    import queue as _stdlib_queue
    import threading as _threading

    from rdf.models.robometer_worker import RobometerLocalWorker

    # decoded_q: producer puts (msg, manifest, frames, err) as each episode
    # finishes decoding; None sentinel signals end-of-stream to the consumer.
    # maxsize caps memory — GPU scores faster than the CPU decodes.
    decoded_q: _stdlib_queue.Queue = _stdlib_queue.Queue(maxsize=_models.decode_queue_maxsize)
    _producer_exc: list = []

    def _run_producer():
        try:
            stream_episodes(
                queue=episode_queue,
                store=store,
                catalog=catalog,
                model_version=_models.robometer_model_version,
                decoded_q=decoded_q,
                max_episodes=max_a,
                n_preprocess_workers=_models.video_preprocess_workers,
            )
        except Exception as exc:
            _producer_exc.append(exc)
            decoded_q.put(None)  # unblock consumer even on error

    producer_thread = _threading.Thread(target=_run_producer, daemon=True)
    producer_thread.start()
    print("  Decoding episodes in background …", flush=True)

    t_model_start = time.monotonic()
    robometer_model = RobometerLocalWorker()
    model_load_s = time.monotonic() - t_model_start
    print(f"  Model loaded in {model_load_s:.1f}s — scoring begins now", flush=True)

    t_a = time.monotonic()
    n_a = run_stage_a(
        model=robometer_model,
        queue=episode_queue,
        store=store,
        catalog=catalog,
        robometer_threshold=robometer_threshold,
        poll_wait=0,
        max_episodes=max_a,
        decoded_stream=decoded_q,
    )
    elapsed_a = time.monotonic() - t_a

    producer_thread.join()
    if _producer_exc:
        raise _producer_exc[0]

    # Report Stage A results — only count episodes that were actually scored
    all_tasks = list({m.task for m in manifests})
    stage_a_pass = 0
    stage_a_drop = 0
    for task in all_tasks:
        rows = catalog.rows_for_task(task)
        for r in rows:
            if r.robometer_pass is True:
                stage_a_pass += 1
            else:
                stage_a_drop += 1
    print(f"  Processed: {n_a}  Pass: {stage_a_pass}  Drop (gate): {stage_a_drop}")
    ms_per = (elapsed_a / n_a * 1000) if n_a else 0
    print(f"  Time: {elapsed_a:.1f}s  ({ms_per:.0f}ms/episode)\n")

    # --- DemInf scoring (runs in openx env as subprocess) ---
    print("[ DemInf Scoring ]")

    # Only process episodes that passed Stage A — drops are excluded from DemInf entirely.
    pass_ep_ids = {
        r.episode_id
        for task in all_tasks
        for r in catalog.rows_for_task(task)
        if r.robometer_pass is True
    }
    pass_manifests = [m for m in manifests if m.episode_id in pass_ep_ids]
    print(f"  Stage A pass: {len(pass_manifests)}/{len(manifests)} episodes forwarded to DemInf")

    added = _setup_deminf_data(pass_manifests)
    task_ids = sorted({m.task_id for m in pass_manifests})
    n_total = sum(
        len(list((DEMINF_DATA / tid / "train").iterdir()))
        for tid in task_ids
        if (DEMINF_DATA / tid / "train").exists()
    )
    if added:
        print(f"  Linked {added} new episodes under {DEMINF_DATA}/{{task_id}}/train/ ({n_total} total)")
    else:
        print(f"  All {n_total} episodes already present  task_ids={task_ids}")

    # Resolve (or auto-train) the VAE checkpoint for each task_id
    ckpts_by_task: dict[str, str] = {}
    for task_id in task_ids:
        ckpt = _get_checkpoint_for_task(task_id)
        if ckpt:
            print(f"  Checkpoint found for task_id={task_id!r}: {ckpt}")
        else:
            print(
                f"  No checkpoint for task_id={task_id!r} — training VAE"
                f" ({_models.deminf_train_episodes} episodes, {_models.deminf_train_steps} steps) …",
                flush=True,
            )
            task_pass_ep_ids = [
                m.episode_id for m in pass_manifests if m.task_id == task_id
            ]
            t_train = time.monotonic()
            ckpt = _train_deminf_for_task(task_id, task_pass_ep_ids)
            print(f"  Training complete in {time.monotonic() - t_train:.1f}s  ckpt={ckpt}")
        ckpts_by_task[task_id] = ckpt

    # Preprocess any uncached pass episodes before scoring (idempotent)
    for task_id in task_ids:
        _preprocess_deminf_data(task_id, splits=["train"])

    print(f"  Running deminf_score_episodes.py for task_ids={task_ids} (openx env) …", flush=True)
    t_deminf = time.monotonic()
    _run_deminf_scoring(pass_manifests, ckpts_by_task)
    elapsed_deminf = time.monotonic() - t_deminf
    print(f"  DemInf scoring complete in {elapsed_deminf:.1f}s\n")

    # --- Cohort accumulation (sequential mode) ---
    print("[ Cohort Accumulation ]")
    from rdf.stage_b_deminf.accumulator import accumulate_sequential
    cohort_ids = accumulate_sequential(
        tasks=all_tasks,
        catalog=catalog,
        cohort_queue=cohort_queue,
        pipeline_cfg=_pipeline,
        vae_version=_pipeline.vae_version,
        reference_set_version=_pipeline.reference_set_version,
    )
    print(f"  Tasks: {all_tasks}")
    print(f"  Cohorts emitted: {len(cohort_ids)}\n")

    # --- Stage B: DemInf lookup ---
    print(f"[ Stage B — DemInf (scores from {_paths.deminf_scores_file}) ]")
    from rdf.models.deminf_worker import DeminfWorker
    deminf_model = DeminfWorker()

    t_b = time.monotonic()
    n_b = run_stage_b(
        model=deminf_model,
        queue=cohort_queue,
        store=store,
        catalog=catalog,
        deminf_threshold=deminf_threshold,
        poll_wait=0,
        max_cohorts=len(cohort_ids),
    )
    elapsed_b = time.monotonic() - t_b
    print(f"  Processed cohorts: {n_b}  Time: {elapsed_b:.1f}s\n")

    # --- Decision ---
    print("[ Decision ]")
    counts: dict[str, int] = {}
    for task in all_tasks:
        c = decide_all(task, catalog, robometer_threshold, deminf_threshold)
        for k, v in c.items():
            counts[k] = counts.get(k, 0) + v

    # --- Final report ---
    total = sum(counts.values())
    elapsed = time.monotonic() - t_start
    print(f"\n{'='*60}")
    print("RESULTS")
    print(f"{'='*60}")
    print(f"  Total episodes  : {total}")
    print(f"  Keep            : {counts.get('keep', 0)}  ({counts.get('keep',0)/total*100:.1f}%)")
    print(f"  Drop            : {counts.get('drop', 0)}  ({counts.get('drop',0)/total*100:.1f}%)")
    print(f"  Pending         : {counts.get('pending', 0)}")
    print(f"  Stage A pass    : {stage_a_pass}/{total}  ({stage_a_pass/total*100:.1f}%)")
    print(f"  Stage A drop    : {stage_a_drop}/{total}  ({stage_a_drop/total*100:.1f}%)")
    print(f"  Total wall time : {elapsed:.1f}s")
    print(f"{'='*60}\n")

    # Per-episode detail (first 20)
    print("Sample decisions (first 20 episodes):")
    print(f"  {'episode_id':<20} {'robometer':>10} {'pass':>6} {'deminf':>10} {'decision':>10}")
    print(f"  {'-'*20} {'-'*10} {'-'*6} {'-'*10} {'-'*10}")
    for task in all_tasks:
        rows = sorted(catalog.rows_for_task(task), key=lambda r: r.episode_id)
        for r in rows[:20]:
            rob = f"{r.robometer_success_pred:.4f}" if r.robometer_success_pred is not None else "N/A"
            deminf_s = f"{r.deminf_score:.4f}" if r.deminf_score is not None else "N/A"
            passed = "YES" if r.robometer_pass else "NO"
            print(f"  {r.episode_id:<20} {rob:>10} {passed:>6} {deminf_s:>10} {r.final_decision:>10}")

    # --- Cleanup: remove cached .npz files now that scoring is done ---
    removed = 0
    for npz in DEMINF_DATA.rglob("*_cached.npz"):
        npz.unlink()
        removed += 1
    if removed:
        print(f"\n  Cleaned up {removed} cached .npz files from {DEMINF_DATA}")


if __name__ == "__main__":
    main()
