"""End-to-end pipeline runner against /data/clean_data/.

Runs all episodes through Stage A (Robometer) → DemInf scoring → cohort
accumulation → Stage B (DemInf lookup) → decision, using a store adapter
that reads directly from /data/clean_data/ without copying any files.

Usage:
    cd /data/reward_model
    RDF_DEMINF_SCORES=/tmp/rdf_deminf_scores.json \\
        /data/robometer/.venv/bin/python3 -u scripts/run_local_pipeline.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# --- make rdf importable without installing ---
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

os.environ.setdefault("RDF_STORAGE", "local")

import time
import uuid
import yaml
from datetime import datetime, timezone

from rdf.harness.catalog import LocalCatalog
from rdf.harness.queue import LocalQueue
from rdf.harness.storage import ObjectStore
from rdf.schemas.models import CatalogRow, CohortMessage, EpisodeManifest, PipelineConfig
from rdf.stage_a_robometer.worker import stream_episodes, run_worker as run_stage_a
from rdf.stage_b_deminf.infer_worker import run_infer_worker as run_stage_b
from rdf.decision.decide import decide_all

CLEAN_DATA = Path("/data/clean_data")
SCRATCH = Path("/tmp/rdf_integration")
SCRATCH.mkdir(parents=True, exist_ok=True)

DEMINF_DATA = Path(os.environ.get("RDF_DEMINF_DATA", "/tmp/rdf_pipeline_deminf/deminf_data"))
_OPENX_PYTHON = "/data/.conda/envs/openx/bin/python3"
_DEMINF_SCORE_SCRIPT = Path(__file__).parent / "deminf_score_episodes.py"


def _setup_deminf_data(manifests: list) -> int:
    """Symlink any missing episodes into DEMINF_DATA/train/ for scoring.

    Each episode dir gets symlinks to its MCAP and MP4 files from clean_data.
    The cached .npz is generated by deminf_score_episodes.py on first run.
    Returns the number of newly linked episodes.
    """
    train_dir = DEMINF_DATA / "train"
    train_dir.mkdir(parents=True, exist_ok=True)
    added = 0
    for m in manifests:
        ep_src = CLEAN_DATA / m.episode_id
        ep_dst = train_dir / m.episode_id
        if ep_dst.exists():
            continue
        ep_dst.mkdir()
        for fname in [
            "cam_head.mp4",
            "cam_wrist.mp4",
            f"{m.episode_id}.mcap",
            "metadata.yaml",
        ]:
            src = ep_src / fname
            if src.exists():
                (ep_dst / fname).symlink_to(src)
        added += 1
    return added


def _run_deminf_scoring(scores_out: str) -> None:
    """Run deminf_score_episodes.py in the openx conda env (blocking).

    Uses DEMINF_DATA as the data root and writes scores to scores_out.
    Checkpoint is auto-detected from /tmp/rdf_deminf_ckpts/*/1000.
    Raises RuntimeError if the subprocess exits non-zero.
    """
    import subprocess

    env = dict(os.environ)
    env["RDF_DEMINF_DATA"] = str(DEMINF_DATA)
    env["RDF_DEMINF_SCORES"] = str(scores_out)
    env["RDF_DEMINF_SPLIT"] = "train"

    proc = subprocess.run(
        [_OPENX_PYTHON, str(_DEMINF_SCORE_SCRIPT)],
        cwd="/data/demonstration-information",
        env=env,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"DemInf scoring subprocess failed (exit {proc.returncode})")


class CleanDataStore(ObjectStore):
    """Read-only adapter: maps pipeline key conventions to /data/clean_data/ layout.

    Key conventions expected by the pipeline:
      raw/{episode_id}/head.mp4   ← cam_head.mp4
      raw/{episode_id}/data.mcap  ← {episode_id}.mcap
      raw/{episode_id}/metadata.yaml
    """

    def _resolve(self, key: str) -> Path | None:
        parts = key.split("/")
        if len(parts) < 3 or parts[0] != "raw":
            return None
        episode_id = parts[1]
        filename = parts[2]
        ep_dir = CLEAN_DATA / episode_id
        if filename == "head.mp4":
            return ep_dir / "cam_head.mp4"
        if filename == "data.mcap":
            # episode_XXXX.mcap
            matches = list(ep_dir.glob("*.mcap"))
            return matches[0] if matches else None
        if filename == "metadata.yaml":
            return ep_dir / "metadata.yaml"
        return None

    def get_bytes(self, key: str) -> bytes:
        p = self._resolve(key)
        if p is None or not p.exists():
            raise FileNotFoundError(key)
        return p.read_bytes()

    def exists(self, key: str) -> bool:
        p = self._resolve(key)
        return p is not None and p.exists()

    def put_bytes(self, key: str, data: bytes) -> None:
        # write to scratch for clean-bucket simulation
        dest = SCRATCH / key
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)

    def delete(self, key: str) -> None:
        p = SCRATCH / key
        if p.exists():
            p.unlink()

    def list_keys(self, prefix: str) -> list[str]:
        # Only enumerate raw/ prefix for known episodes
        if prefix.startswith("raw/"):
            parts = prefix.split("/")
            if len(parts) >= 2:
                ep_dir = CLEAN_DATA / parts[1]
                if ep_dir.exists():
                    return [
                        f"raw/{parts[1]}/head.mp4",
                        f"raw/{parts[1]}/data.mcap",
                        f"raw/{parts[1]}/metadata.yaml",
                    ]
        return []


def _parse_metadata(episode_id: str) -> dict:
    meta_path = CLEAN_DATA / episode_id / "metadata.yaml"
    meta = yaml.safe_load(meta_path.read_text())
    # Adapt field names to what EpisodeManifest expects
    tasks = meta.get("tasks", [])
    task = tasks[0] if tasks else meta.get("task", "unknown")
    return {
        "task": task,
        "instruction": task,  # no instruction field in these files
        "embodiment": meta.get("robot_type", "unknown"),
        "robot_id": meta.get("robot_id", "unknown"),
    }


def build_manifests(instruction_override: str | None = None) -> list[EpisodeManifest]:
    manifests = []
    for ep_dir in sorted(CLEAN_DATA.iterdir()):
        if not ep_dir.is_dir():
            continue
        episode_id = ep_dir.name
        fields = _parse_metadata(episode_id)
        instruction = instruction_override or fields["instruction"]
        m = EpisodeManifest(
            episode_id=episode_id,
            s3_prefix=f"raw/{episode_id}/",
            robot_id=fields["robot_id"],
            embodiment=fields["embodiment"],
            task=fields["task"],
            instruction=instruction,
            head_video_key=f"raw/{episode_id}/head.mp4",
            mcap_key=f"raw/{episode_id}/data.mcap",
            metadata_key=f"raw/{episode_id}/metadata.yaml",
            created_at=datetime.now(timezone.utc),
        )
        manifests.append(m)
    return manifests


def main():
    t_start = time.monotonic()
    print(f"\n{'='*60}")
    print("RDF Pipeline — Local Integration Test")
    print(f"Data: {CLEAN_DATA}  Scratch: {SCRATCH}")
    print(f"{'='*60}\n")

    store = CleanDataStore()
    catalog = LocalCatalog(root=str(SCRATCH / "catalog"))
    episode_queue = LocalQueue("rdf-episodes", root=str(SCRATCH / "queues"))
    cohort_queue = LocalQueue("rdf-cohorts", root=str(SCRATCH / "queues"))

    # --- Ingestion: build manifests, seed catalog, enqueue ---
    print("[ Ingestion ]")
    instruction_override = os.environ.get("RDF_INSTRUCTION")
    if instruction_override:
        print(f"  Instruction override: {instruction_override!r}")
    manifests = build_manifests(instruction_override=instruction_override)
    print(f"  Found {len(manifests)} episodes")
    now = datetime.now(timezone.utc)
    for m in manifests:
        catalog.upsert_row(CatalogRow(
            episode_id=m.episode_id,
            task=m.task,
            embodiment=m.embodiment,
            robot_id=m.robot_id,
            pipeline_mode="sequential",
            created_at=now,
            updated_at=now,
        ))
        episode_queue.enqueue(m.model_dump(mode="json"), dedup_id=m.episode_id)
    print(f"  Seeded catalog and enqueued {len(manifests)} episodes\n")

    # --- Stage A: Robometer scoring ---
    print("[ Stage A — Robometer ]")
    robometer_threshold = float(os.environ.get("RDF_ROBOMETER_THRESHOLD", "0.5"))
    max_a = int(os.environ.get("RDF_MAX_EPISODES", len(manifests)))
    if max_a < len(manifests):
        print(f"  (smoke-test mode: processing {max_a}/{len(manifests)} episodes)")

    import queue as _stdlib_queue
    import threading as _threading
    from rdf.models.robometer_worker import RobometerLocalWorker

    # decoded_q: producer puts (msg, manifest, frames, err) as each episode
    # finishes decoding; None sentinel signals end-of-stream to the consumer.
    # maxsize=8 caps memory — GPU scores faster than the CPU decodes, so the
    # queue usually drains before it fills.
    decoded_q: _stdlib_queue.Queue = _stdlib_queue.Queue(maxsize=8)
    _producer_exc: list = []

    def _run_producer():
        try:
            stream_episodes(
                queue=episode_queue,
                store=store,
                catalog=catalog,
                model_version="Robometer-4B",
                decoded_q=decoded_q,
                max_episodes=max_a,
            )
        except Exception as exc:
            _producer_exc.append(exc)
            decoded_q.put(None)  # unblock consumer even on error

    producer_thread = _threading.Thread(target=_run_producer, daemon=True)
    producer_thread.start()
    print("  Decoding episodes in background …", flush=True)

    t_model_start = time.monotonic()
    robometer_model = RobometerLocalWorker()
    model_load_s = time.monotonic() - t_model_start
    print(f"  Model loaded in {model_load_s:.1f}s — scoring begins now", flush=True)

    t_a = time.monotonic()
    n_a = run_stage_a(
        model=robometer_model,
        queue=episode_queue,
        store=store,
        catalog=catalog,
        robometer_threshold=robometer_threshold,
        poll_wait=0,
        max_episodes=max_a,
        decoded_stream=decoded_q,
    )
    elapsed_a = time.monotonic() - t_a

    producer_thread.join()
    if _producer_exc:
        raise _producer_exc[0]

    # Report Stage A results — only count episodes that were actually scored
    all_tasks = list({m.task for m in manifests})
    stage_a_pass = 0
    stage_a_drop = 0
    for task in all_tasks:
        rows = catalog.rows_for_task(task)
        for r in rows:
            if r.robometer_pass is True:
                stage_a_pass += 1
            else:
                stage_a_drop += 1
    print(f"  Processed: {n_a}  Pass: {stage_a_pass}  Drop (gate): {stage_a_drop}")
    ms_per = (elapsed_a / n_a * 1000) if n_a else 0
    print(f"  Time: {elapsed_a:.1f}s  ({ms_per:.0f}ms/episode)\n")

    # --- DemInf scoring (runs in openx env as subprocess) ---
    deminf_scores_file = os.environ.get("RDF_DEMINF_SCORES", "/tmp/rdf_deminf_scores.json")
    print("[ DemInf Scoring ]")
    added = _setup_deminf_data(manifests)
    n_train = len(list((DEMINF_DATA / "train").iterdir()))
    if added:
        print(f"  Linked {added} new episodes → {DEMINF_DATA}/train/ ({n_train} total)")
    else:
        print(f"  All {n_train} episodes already present in {DEMINF_DATA}/train/")
    print("  Running deminf_score_episodes.py (openx env) …", flush=True)
    t_deminf = time.monotonic()
    _run_deminf_scoring(deminf_scores_file)
    elapsed_deminf = time.monotonic() - t_deminf
    print(f"  DemInf scoring complete in {elapsed_deminf:.1f}s\n")

    # --- Cohort accumulation (sequential mode) ---
    print("[ Cohort Accumulation ]")
    from rdf.stage_b_deminf.accumulator import accumulate_sequential
    pipeline_cfg = PipelineConfig()
    cohort_ids = accumulate_sequential(
        tasks=all_tasks,
        catalog=catalog,
        cohort_queue=cohort_queue,
        pipeline_cfg=pipeline_cfg,
        vae_version="v1",
        reference_set_version="v1",
    )
    print(f"  Tasks: {all_tasks}")
    print(f"  Cohorts emitted: {len(cohort_ids)}\n")

    # --- Stage B: DemInf lookup ---
    print(f"[ Stage B — DemInf (scores from {deminf_scores_file}) ]")
    from rdf.models.deminf_worker import DeminfWorker
    deminf_model = DeminfWorker(scores_file=deminf_scores_file)
    deminf_threshold = float(os.environ.get("RDF_DEMINF_THRESHOLD", "-10.0"))

    t_b = time.monotonic()
    n_b = run_stage_b(
        model=deminf_model,
        queue=cohort_queue,
        store=store,
        catalog=catalog,
        deminf_threshold=deminf_threshold,
        poll_wait=0,
        max_cohorts=len(cohort_ids),
    )
    elapsed_b = time.monotonic() - t_b
    print(f"  Processed cohorts: {n_b}  Time: {elapsed_b:.1f}s\n")

    # --- Decision ---
    print("[ Decision ]")
    counts: dict[str, int] = {}
    for task in all_tasks:
        c = decide_all(task, catalog, robometer_threshold, deminf_threshold)
        for k, v in c.items():
            counts[k] = counts.get(k, 0) + v

    # --- Final report ---
    total = sum(counts.values())
    elapsed = time.monotonic() - t_start
    print(f"\n{'='*60}")
    print("RESULTS")
    print(f"{'='*60}")
    print(f"  Total episodes  : {total}")
    print(f"  Keep            : {counts.get('keep', 0)}  ({counts.get('keep',0)/total*100:.1f}%)")
    print(f"  Drop            : {counts.get('drop', 0)}  ({counts.get('drop',0)/total*100:.1f}%)")
    print(f"  Pending         : {counts.get('pending', 0)}")
    print(f"  Stage A pass    : {stage_a_pass}/{total}  ({stage_a_pass/total*100:.1f}%)")
    print(f"  Stage A drop    : {stage_a_drop}/{total}  ({stage_a_drop/total*100:.1f}%)")
    print(f"  Total wall time : {elapsed:.1f}s")
    print(f"{'='*60}\n")

    # Per-episode detail (first 20)
    print("Sample decisions (first 20 episodes):")
    print(f"  {'episode_id':<20} {'robometer':>10} {'pass':>6} {'deminf':>10} {'decision':>10}")
    print(f"  {'-'*20} {'-'*10} {'-'*6} {'-'*10} {'-'*10}")
    for task in all_tasks:
        rows = sorted(catalog.rows_for_task(task), key=lambda r: r.episode_id)
        for r in rows[:20]:
            rob = f"{r.robometer_success_pred:.4f}" if r.robometer_success_pred is not None else "N/A"
            deminf_s = f"{r.deminf_score:.4f}" if r.deminf_score is not None else "N/A"
            passed = "YES" if r.robometer_pass else "NO"
            print(f"  {r.episode_id:<20} {rob:>10} {passed:>6} {deminf_s:>10} {r.final_decision:>10}")


if __name__ == "__main__":
    main()
