"""End-to-end pipeline runner.

Runs all episodes through Stage A (Robometer) → DemInf scoring → cohort
accumulation → Stage B (DemInf lookup) → decision, using a store adapter
that reads directly from configs/paths.yaml::clean_data_dir without copying files.

Usage:
    cd /data/reward_model
    /data/robometer/.venv/bin/python3 -u scripts/run_local_pipeline.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# --- make rdf importable without installing ---
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

os.environ.setdefault("RDF_STORAGE", "local")

import time
from datetime import datetime, timezone

import yaml

from rdf.decision.decide import decide_all
from rdf.harness.catalog import LocalCatalog
from rdf.harness.config import get_models_config, get_paths_config, get_pipeline_config
from rdf.harness.queue import LocalQueue
from rdf.harness.storage import ObjectStore
from rdf.schemas.models import CatalogRow, EpisodeManifest
from rdf.stage_a_robometer.worker import run_worker as run_stage_a
from rdf.stage_a_robometer.worker import stream_episodes
from rdf.stage_b_deminf.infer_worker import run_infer_worker as run_stage_b

_paths = get_paths_config()
_pipeline = get_pipeline_config()
_models = get_models_config()

CLEAN_DATA = Path(_paths.clean_data_dir)
SCRATCH = Path(_paths.scratch_dir)
SCRATCH.mkdir(parents=True, exist_ok=True)

DEMINF_DATA = Path(_paths.deminf_data_dir)
_OPENX_PYTHON = _paths.openx_python
_DEMINF_SCORE_SCRIPT = Path(__file__).parent / "deminf_score_episodes.py"


def _setup_deminf_data(manifests: list) -> int:
    """Symlink any missing episodes into DEMINF_DATA/{task_id}/train/ for scoring.

    Each episode dir gets symlinks to its MCAP and MP4 files from clean_data.
    Supports both old Franka layout (cam_head.mp4, {ep}.mcap) and new Manav layout
    ({ep}_head_cam.mp4, {ep}_0.mcap). A canonical {ep}.mcap symlink is always
    created so _mcap_split_dirs can find the episode directory.

    The cached .npz is generated by preprocess_*_episodes.py on first run.
    Returns the number of newly linked episodes.
    """
    added = 0
    for m in manifests:
        train_dir = DEMINF_DATA / m.task_id / "train"
        train_dir.mkdir(parents=True, exist_ok=True)
        ep_src = CLEAN_DATA / m.episode_id
        ep_dst = train_dir / m.episode_id
        if ep_dst.exists():
            continue
        ep_dst.mkdir()

        old_mcap = ep_src / f"{m.episode_id}.mcap"
        new_mcap = ep_src / f"{m.episode_id}_0.mcap"

        if old_mcap.exists():
            # Old Franka layout
            for fname in ["cam_head.mp4", "cam_wrist.mp4", f"{m.episode_id}.mcap", "metadata.yaml"]:
                src = ep_src / fname
                if src.exists():
                    (ep_dst / fname).symlink_to(src)
        else:
            # New Manav layout: {ep}_head_cam.mp4, {ep}_0.mcap
            # Create {ep}.mcap alias so _mcap_split_dirs finds the dir
            if new_mcap.exists():
                (ep_dst / f"{m.episode_id}.mcap").symlink_to(new_mcap)
            for suffix in [f"{m.episode_id}_head_cam.mp4", f"{m.episode_id}_0.mcap", "metadata.yaml"]:
                src = ep_src / suffix
                if src.exists():
                    (ep_dst / suffix).symlink_to(src)

        added += 1
    return added


def _get_checkpoints_for_task(task_id: str) -> dict[str, str] | None:
    """Return {"obs": path, "action": path} for task_id, or None if either is missing.

    Looks in {task_ckpt_dir}/obs_vae/ and {task_ckpt_dir}/action_vae/.
    Prefers the configured deminf_train_steps; falls back to highest available step.
    """
    task_ckpt_dir = Path(_paths.deminf_ckpts_dir) / task_id
    if not task_ckpt_dir.exists():
        return None

    def _best(subdir: str) -> str | None:
        d = task_ckpt_dir / subdir
        if not d.exists():
            return None
        target = d / str(_models.deminf_train_steps)
        if target.exists():
            return str(target)
        steps = sorted(
            [p for p in d.iterdir() if p.name.isdigit()],
            key=lambda p: int(p.name),
        )
        return str(steps[-1]) if steps else None

    obs = _best("obs_vae")
    action = _best("action_vae")
    if obs and action:
        return {"obs": obs, "action": action}
    return None


def _setup_training_data(task_id: str, pass_episode_ids: list[str]) -> None:
    """Create train_sel/ and test_sel/ under DEMINF_DATA/{task_id} for VAE training.

    Symlinks up to deminf_train_episodes Stage-A-pass episodes into train_sel/.
    Uses the first 5 of those as the validation split (test_sel/).
    """
    selected = pass_episode_ids[: _models.deminf_train_episodes]
    task_data = DEMINF_DATA / task_id
    for split_name, eps in [("train_sel", selected), ("test_sel", selected[:5])]:
        split_dir = task_data / split_name
        split_dir.mkdir(exist_ok=True)
        for ep_id in eps:
            src = task_data / "train" / ep_id
            dst = split_dir / ep_id
            if src.exists() and not dst.exists():
                dst.symlink_to(src)


def _is_manav_dataset() -> bool:
    """Return True when clean_data_dir uses the new Manav MCAP layout ({ep}_0.mcap)."""
    for ep_dir in CLEAN_DATA.iterdir():
        if not ep_dir.is_dir() or ep_dir.name in ("failed", "INDEX.log"):
            continue
        mcap_files = list(ep_dir.glob("*_0.mcap"))
        return len(mcap_files) > 0
    return False


def _preprocess_deminf_data(task_id: str, splits: list[str]) -> None:
    """Generate _cached.npz files for the given splits before training.

    For Manav MCAP data ({ep}_0.mcap), calls preprocess_manav_episodes.py
    which reads native ROS2 CDR topics to produce the 32/36-dim state/action arrays.
    For old Franka MCAP data, calls preprocess_episodes.py from demonstration-information.
    Idempotent — already-cached episodes are skipped.
    """
    import subprocess

    task_data = DEMINF_DATA / task_id
    if _is_manav_dataset():
        preprocess_script = Path(__file__).parent / "preprocess_manav_episodes.py"
        proc = subprocess.run(
            [
                _OPENX_PYTHON,
                str(preprocess_script),
                f"--root={task_data}",
                "--splits", *splits,
                f"--workers={_models.video_preprocess_workers}",
            ],
            cwd=_paths.deminf_root,
        )
    else:
        preprocess_script = Path(_paths.deminf_root) / "scripts" / "preprocess_episodes.py"
        proc = subprocess.run(
            [
                _OPENX_PYTHON,
                str(preprocess_script),
                f"--root={task_data}",
                "--splits", *splits,
                f"--workers={_models.video_preprocess_workers}",
            ],
            cwd=_paths.deminf_root,
        )
    if proc.returncode != 0:
        raise RuntimeError(
            f"DemInf preprocessing failed for task_id={task_id!r} splits={splits}"
            f" (exit {proc.returncode})"
        )


def _train_deminf_for_task(task_id: str, pass_episode_ids: list[str]) -> dict[str, str]:
    """Train obs_vae and action_vae for task_id and return {"obs": path, "action": path}.

    Steps:
      1. Create train_sel/ and test_sel/ symlinks (subset of pass episodes).
      2. Preprocess those episodes to _cached.npz so training loads instantly.
      3. For Manav datasets, pre-generate dataset_statistics_openx.json.
      4. Train obs_vae (state-only, config_str="obs").
      5. Train action_vae (action-chunk-only, config_str="action").

    Checkpoints land at:
      deminf_ckpts_dir/{task_id}/obs_vae/{step}/
      deminf_ckpts_dir/{task_id}/action_vae/{step}/
    """
    import subprocess

    output_dir = Path(_paths.deminf_ckpts_dir) / task_id
    output_dir.mkdir(parents=True, exist_ok=True)
    _setup_training_data(task_id, pass_episode_ids)
    _preprocess_deminf_data(task_id, splits=["train_sel", "test_sel"])

    # For Manav MCAP data, pre-generate dataset statistics from npz files.
    # _compute_mcap_statistics in lerobot.py reads MCAP files directly (JSON-encoded
    # topics only) and fails on native CDR messages. We generate the stats cache
    # ourselves and pass recompute_statistics=False so lerobot uses our file.
    if _is_manav_dataset():
        stats_script = Path(__file__).parent / "compute_manav_stats.py"
        proc_stats = subprocess.run(
            [
                _OPENX_PYTHON,
                str(stats_script),
                f"--task_data={DEMINF_DATA / task_id}",
                "--split=train_sel",
            ],
            cwd=_paths.deminf_root,
        )
        if proc_stats.returncode != 0:
            raise RuntimeError(
                f"Manav stats computation failed for task_id={task_id!r}"
                f" (exit {proc_stats.returncode})"
            )

    train_script = Path(_paths.deminf_root) / "scripts" / "train.py"
    config_path = Path(__file__).parent.parent / "configs" / "quality" / "clean_data_vae.py"

    env = os.environ.copy()
    env["RDF_DEMINF_DATA"] = str(DEMINF_DATA / task_id)

    recompute_flag = (
        "--config.dataloader.recompute_statistics=False"
        if _is_manav_dataset()
        else "--config.dataloader.recompute_statistics=True"
    )

    for vae_name, cfg_str in [("obs_vae", "obs"), ("action_vae", "action")]:
        print(f"  Training {vae_name} (config_str={cfg_str!r}) …", flush=True)
        # --config must come before any --config.* overrides (ml_collections requirement)
        proc = subprocess.run(
            [
                _OPENX_PYTHON,
                str(train_script),
                f"--config={config_path}:{cfg_str}",
                f"--path={output_dir}",
                f"--name={vae_name}",
                "--include_timestamp=False",
                f"--config.steps={_models.deminf_train_steps}",
                f"--config.save_freq={_models.deminf_train_save_freq}",
                "--config.dataloader.datasets.clean_data.train_split=train_sel",
                "--config.dataloader.datasets.clean_data.val_split=test_sel",
                recompute_flag,
            ],
            cwd=_paths.deminf_root,
            env=env,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"DemInf {vae_name} training failed for task_id={task_id!r}"
                f" (exit {proc.returncode})"
            )

    ckpts = _get_checkpoints_for_task(task_id)
    if not ckpts:
        raise RuntimeError(f"Checkpoints not found after training for task_id={task_id!r}")
    return ckpts


def _run_deminf_scoring(manifests: list, ckpts_by_task: dict[str, dict[str, str]]) -> None:
    """Run deminf_score_episodes.py once per task_id using separate obs + action checkpoints.

    Each run gets RDF_DEMINF_DATA → DEMINF_DATA/{task_id},
    RDF_DEMINF_OBS_CKPT and RDF_DEMINF_ACTION_CKPT for that task.
    Per-task scores are merged into the single shared scores file.
    """
    import json
    import subprocess
    import tempfile
    from collections import defaultdict

    by_task: dict[str, list] = defaultdict(list)
    for m in manifests:
        by_task[m.task_id].append(m)

    all_scores: dict[str, float] = {}
    last_obs_ckpt = ""

    for task_id in sorted(by_task):
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp_scores = f.name
        ckpts = ckpts_by_task[task_id]
        env = os.environ.copy()
        env["RDF_DEMINF_DATA"] = str(DEMINF_DATA / task_id)
        env["RDF_DEMINF_OBS_CKPT"] = ckpts["obs"]
        env["RDF_DEMINF_ACTION_CKPT"] = ckpts["action"]
        env["RDF_DEMINF_SCORES"] = tmp_scores
        proc = subprocess.run(
            [_OPENX_PYTHON, str(_DEMINF_SCORE_SCRIPT)],
            cwd=_paths.deminf_root,
            env=env,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"DemInf scoring failed for task_id={task_id!r} (exit {proc.returncode})"
            )
        with open(tmp_scores) as f:
            data = json.load(f)
        all_scores.update(data.get("scores", {}))
        last_obs_ckpt = data.get("obs_ckpt", last_obs_ckpt)
        os.unlink(tmp_scores)

    scores_out = Path(_paths.deminf_scores_file)
    scores_out.parent.mkdir(parents=True, exist_ok=True)
    scores_out.write_text(
        json.dumps(
            {"scores": all_scores, "split": _models.deminf_split, "obs_ckpt": last_obs_ckpt},
            indent=2,
        )
    )


class CleanDataStore(ObjectStore):
    """Read-only adapter: maps pipeline key conventions to clean_data_dir layout.

    Supports two layouts:
      Old Franka: cam_head.mp4, {episode_id}.mcap
      New Manav:  {episode_id}_head_cam.mp4, {episode_id}_0.mcap

    Key conventions expected by the pipeline:
      raw/{episode_id}/head.mp4   ← cam_head.mp4 OR {episode_id}_head_cam.mp4
      raw/{episode_id}/data.mcap  ← {episode_id}.mcap OR {episode_id}_0.mcap
      raw/{episode_id}/metadata.yaml
    """

    def _resolve(self, key: str) -> Path | None:
        parts = key.split("/")
        if len(parts) < 3 or parts[0] != "raw":
            return None
        episode_id = parts[1]
        filename = parts[2]
        ep_dir = CLEAN_DATA / episode_id
        if filename == "head.mp4":
            # Try old Franka layout first, then new Manav layout
            old = ep_dir / "cam_head.mp4"
            if old.exists():
                return old
            return ep_dir / f"{episode_id}_head_cam.mp4"
        if filename == "data.mcap":
            old = ep_dir / f"{episode_id}.mcap"
            if old.exists():
                return old
            # New Manav: {episode_id}_0.mcap
            matches = list(ep_dir.glob("*_0.mcap"))
            return matches[0] if matches else None
        if filename == "metadata.yaml":
            return ep_dir / "metadata.yaml"
        return None

    def get_bytes(self, key: str) -> bytes:
        p = self._resolve(key)
        if p is None or not p.exists():
            raise FileNotFoundError(key)
        return p.read_bytes()

    def exists(self, key: str) -> bool:
        p = self._resolve(key)
        return p is not None and p.exists()

    def put_bytes(self, key: str, data: bytes) -> None:
        # write to scratch for clean-bucket simulation
        dest = SCRATCH / key
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)

    def delete(self, key: str) -> None:
        p = SCRATCH / key
        if p.exists():
            p.unlink()

    def list_keys(self, prefix: str) -> list[str]:
        # Only enumerate raw/ prefix for known episodes
        if prefix.startswith("raw/"):
            parts = prefix.split("/")
            if len(parts) >= 2:
                ep_dir = CLEAN_DATA / parts[1]
                if ep_dir.exists():
                    return [
                        f"raw/{parts[1]}/head.mp4",
                        f"raw/{parts[1]}/data.mcap",
                        f"raw/{parts[1]}/metadata.yaml",
                    ]
        return []


def _parse_metadata(episode_id: str) -> dict:
    meta_path = CLEAN_DATA / episode_id / "metadata.yaml"
    meta = yaml.safe_load(meta_path.read_text())
    tasks = meta.get("tasks", [])
    task = tasks[0] if tasks else meta.get("task", meta.get("session_name", "unknown"))
    task_id = meta.get("task_id")
    if task_id is None:
        print(
            f"  WARNING: {episode_id}/metadata.yaml has no task_id field"
            f" — using default_task_id={_pipeline.default_task_id!r}",
            flush=True,
        )
        task_id = _pipeline.default_task_id
    else:
        task_id = str(task_id)
    return {
        "task": task,
        "task_id": task_id,
        "instruction": meta.get("instruction", task),
        "embodiment": meta.get("robot_type", meta.get("embodiment", "manav_dual_arm")),
        "robot_id": meta.get("robot_id", "unknown"),
    }


def build_manifests(instruction_override: str | None = None) -> list[EpisodeManifest]:
    manifests = []
    for ep_dir in sorted(CLEAN_DATA.iterdir()):
        if not ep_dir.is_dir():
            continue
        # Skip the failed/ subdirectory and any non-episode files/dirs
        if ep_dir.name in ("failed",) or not (ep_dir / "metadata.yaml").exists():
            continue
        episode_id = ep_dir.name
        fields = _parse_metadata(episode_id)
        instruction = instruction_override or fields["instruction"]
        m = EpisodeManifest(
            episode_id=episode_id,
            s3_prefix=f"raw/{episode_id}/",
            robot_id=fields["robot_id"],
            embodiment=fields["embodiment"],
            task=fields["task"],
            task_id=fields["task_id"],
            instruction=instruction,
            head_video_key=f"raw/{episode_id}/head.mp4",
            mcap_key=f"raw/{episode_id}/data.mcap",
            metadata_key=f"raw/{episode_id}/metadata.yaml",
            created_at=datetime.now(timezone.utc),
        )
        manifests.append(m)
    return manifests


def main():
    t_start = time.monotonic()
    print(f"\n{'='*60}")
    print("RDF Pipeline — Local Integration Test")
    print(f"Data: {CLEAN_DATA}  Scratch: {SCRATCH}")
    print(f"{'='*60}\n")

    store = CleanDataStore()
    catalog = LocalCatalog(root=str(SCRATCH / "catalog"))
    episode_queue = LocalQueue("rdf-episodes", root=str(SCRATCH / "queues"))
    cohort_queue = LocalQueue("rdf-cohorts", root=str(SCRATCH / "queues"))

    robometer_threshold = _pipeline.robometer_threshold
    deminf_threshold = _pipeline.deminf_threshold

    # --- Ingestion: build manifests, seed catalog, enqueue ---
    print("[ Ingestion ]")
    instruction_override = os.environ.get("RDF_INSTRUCTION")
    if instruction_override:
        print(f"  Instruction override: {instruction_override!r}")
    manifests = build_manifests(instruction_override=instruction_override)
    print(f"  Found {len(manifests)} episodes")
    now = datetime.now(timezone.utc)
    for m in manifests:
        catalog.upsert_row(CatalogRow(
            episode_id=m.episode_id,
            task=m.task,
            embodiment=m.embodiment,
            robot_id=m.robot_id,
            pipeline_mode=_pipeline.mode,
            created_at=now,
            updated_at=now,
        ))
        episode_queue.enqueue(m.model_dump(mode="json"), dedup_id=m.episode_id)
    print(f"  Seeded catalog and enqueued {len(manifests)} episodes\n")

    # --- Stage A: Robometer scoring ---
    print("[ Stage A — Robometer ]")
    max_a = int(os.environ.get("RDF_MAX_EPISODES", len(manifests)))
    if max_a < len(manifests):
        print(f"  (smoke-test mode: processing {max_a}/{len(manifests)} episodes)")

    import queue as _stdlib_queue
    import threading as _threading

    from rdf.models.robometer_worker import RobometerLocalWorker

    # decoded_q: producer puts (msg, manifest, frames, err) as each episode
    # finishes decoding; None sentinel signals end-of-stream to the consumer.
    # maxsize caps memory — GPU scores faster than the CPU decodes.
    decoded_q: _stdlib_queue.Queue = _stdlib_queue.Queue(maxsize=_models.decode_queue_maxsize)
    _producer_exc: list = []

    def _run_producer():
        try:
            stream_episodes(
                queue=episode_queue,
                store=store,
                catalog=catalog,
                model_version=_models.robometer_model_version,
                decoded_q=decoded_q,
                max_episodes=max_a,
                n_preprocess_workers=_models.video_preprocess_workers,
            )
        except Exception as exc:
            _producer_exc.append(exc)
            decoded_q.put(None)  # unblock consumer even on error

    producer_thread = _threading.Thread(target=_run_producer, daemon=True)
    producer_thread.start()
    print("  Decoding episodes in background …", flush=True)

    t_model_start = time.monotonic()
    robometer_model = RobometerLocalWorker()
    model_load_s = time.monotonic() - t_model_start
    print(f"  Model loaded in {model_load_s:.1f}s — scoring begins now", flush=True)

    t_a = time.monotonic()
    n_a = run_stage_a(
        model=robometer_model,
        queue=episode_queue,
        store=store,
        catalog=catalog,
        robometer_threshold=robometer_threshold,
        poll_wait=0,
        max_episodes=max_a,
        decoded_stream=decoded_q,
    )
    elapsed_a = time.monotonic() - t_a

    producer_thread.join()
    if _producer_exc:
        raise _producer_exc[0]

    # Report Stage A results — only count episodes that were actually scored
    all_tasks = list({m.task for m in manifests})
    stage_a_pass = 0
    stage_a_drop = 0
    for task in all_tasks:
        rows = catalog.rows_for_task(task)
        for r in rows:
            if r.robometer_pass is True:
                stage_a_pass += 1
            else:
                stage_a_drop += 1
    print(f"  Processed: {n_a}  Pass: {stage_a_pass}  Drop (gate): {stage_a_drop}")
    ms_per = (elapsed_a / n_a * 1000) if n_a else 0
    print(f"  Time: {elapsed_a:.1f}s  ({ms_per:.0f}ms/episode)\n")

    # --- DemInf scoring (runs in openx env as subprocess) ---
    print("[ DemInf Scoring ]")

    # Only process episodes that passed Stage A — drops are excluded from DemInf entirely.
    pass_ep_ids = {
        r.episode_id
        for task in all_tasks
        for r in catalog.rows_for_task(task)
        if r.robometer_pass is True
    }
    pass_manifests = [m for m in manifests if m.episode_id in pass_ep_ids]
    print(f"  Stage A pass: {len(pass_manifests)}/{len(manifests)} episodes forwarded to DemInf")

    added = _setup_deminf_data(pass_manifests)
    task_ids = sorted({m.task_id for m in pass_manifests})
    n_total = sum(
        len(list((DEMINF_DATA / tid / "train").iterdir()))
        for tid in task_ids
        if (DEMINF_DATA / tid / "train").exists()
    )
    if added:
        print(f"  Linked {added} new episodes under {DEMINF_DATA}/{{task_id}}/train/ ({n_total} total)")
    else:
        print(f"  All {n_total} episodes already present  task_ids={task_ids}")

    # Resolve (or auto-train) obs_vae + action_vae checkpoints for each task_id
    ckpts_by_task: dict[str, dict[str, str]] = {}
    for task_id in task_ids:
        ckpts = _get_checkpoints_for_task(task_id)
        if ckpts:
            print(f"  Checkpoints found for task_id={task_id!r}:")
            print(f"    obs_vae    : {ckpts['obs']}")
            print(f"    action_vae : {ckpts['action']}")
        else:
            print(
                f"  No checkpoints for task_id={task_id!r} —"
                f" training obs_vae + action_vae"
                f" ({_models.deminf_train_episodes} eps,"
                f" {_models.deminf_train_steps} steps) …",
                flush=True,
            )
            task_pass_ep_ids = [
                m.episode_id for m in pass_manifests if m.task_id == task_id
            ]
            t_train = time.monotonic()
            ckpts = _train_deminf_for_task(task_id, task_pass_ep_ids)
            print(
                f"  Training complete in {time.monotonic() - t_train:.1f}s"
                f"  obs={ckpts['obs']}  action={ckpts['action']}"
            )
        ckpts_by_task[task_id] = ckpts

    # Preprocess any uncached pass episodes before scoring (idempotent)
    for task_id in task_ids:
        _preprocess_deminf_data(task_id, splits=["train"])

    print(f"  Running deminf_score_episodes.py for task_ids={task_ids} (openx env) …", flush=True)
    t_deminf = time.monotonic()
    _run_deminf_scoring(pass_manifests, ckpts_by_task)
    elapsed_deminf = time.monotonic() - t_deminf
    print(f"  DemInf scoring complete in {elapsed_deminf:.1f}s\n")

    # Compute percentile-based threshold if configured
    if _pipeline.deminf_filter_bottom_pct > 0.0:
        import json as _json
        scores_data = _json.loads(Path(_paths.deminf_scores_file).read_text())
        score_vals = sorted(scores_data["scores"].values())
        pct = _pipeline.deminf_filter_bottom_pct
        cutoff_idx = int(len(score_vals) * pct)
        deminf_threshold = score_vals[cutoff_idx]
        print(
            f"  Percentile filter: bottom {pct*100:.0f}% → threshold={deminf_threshold:.4f}"
            f"  (cutoff at rank {cutoff_idx}/{len(score_vals)})\n"
        )

    # --- Cohort accumulation (sequential mode) ---
    print("[ Cohort Accumulation ]")
    from rdf.stage_b_deminf.accumulator import accumulate_sequential
    cohort_ids = accumulate_sequential(
        tasks=all_tasks,
        catalog=catalog,
        cohort_queue=cohort_queue,
        pipeline_cfg=_pipeline,
        vae_version=_pipeline.vae_version,
        reference_set_version=_pipeline.reference_set_version,
    )
    print(f"  Tasks: {all_tasks}")
    print(f"  Cohorts emitted: {len(cohort_ids)}\n")

    # --- Stage B: DemInf lookup ---
    print(f"[ Stage B — DemInf (scores from {_paths.deminf_scores_file}) ]")
    from rdf.models.deminf_worker import DeminfWorker
    deminf_model = DeminfWorker()

    t_b = time.monotonic()
    n_b = run_stage_b(
        model=deminf_model,
        queue=cohort_queue,
        store=store,
        catalog=catalog,
        deminf_threshold=deminf_threshold,
        poll_wait=0,
        max_cohorts=len(cohort_ids),
    )
    elapsed_b = time.monotonic() - t_b
    print(f"  Processed cohorts: {n_b}  Time: {elapsed_b:.1f}s\n")

    # --- Decision ---
    print("[ Decision ]")
    counts: dict[str, int] = {}
    for task in all_tasks:
        c = decide_all(task, catalog, robometer_threshold, deminf_threshold)
        for k, v in c.items():
            counts[k] = counts.get(k, 0) + v

    # --- Final report ---
    total = sum(counts.values())
    elapsed = time.monotonic() - t_start
    print(f"\n{'='*60}")
    print("RESULTS")
    print(f"{'='*60}")
    print(f"  Total episodes  : {total}")
    print(f"  Keep            : {counts.get('keep', 0)}  ({counts.get('keep',0)/total*100:.1f}%)")
    print(f"  Drop            : {counts.get('drop', 0)}  ({counts.get('drop',0)/total*100:.1f}%)")
    print(f"  Pending         : {counts.get('pending', 0)}")
    print(f"  Stage A pass    : {stage_a_pass}/{total}  ({stage_a_pass/total*100:.1f}%)")
    print(f"  Stage A drop    : {stage_a_drop}/{total}  ({stage_a_drop/total*100:.1f}%)")
    print(f"  Total wall time : {elapsed:.1f}s")
    print(f"{'='*60}\n")

    # Per-episode detail (first 20)
    print("Sample decisions (first 20 episodes):")
    print(f"  {'episode_id':<20} {'robometer':>10} {'pass':>6} {'deminf':>10} {'decision':>10}")
    print(f"  {'-'*20} {'-'*10} {'-'*6} {'-'*10} {'-'*10}")
    for task in all_tasks:
        rows = sorted(catalog.rows_for_task(task), key=lambda r: r.episode_id)
        for r in rows[:20]:
            rob = f"{r.robometer_success_pred:.4f}" if r.robometer_success_pred is not None else "N/A"
            deminf_s = f"{r.deminf_score:.4f}" if r.deminf_score is not None else "N/A"
            passed = "YES" if r.robometer_pass else "NO"
            print(f"  {r.episode_id:<20} {rob:>10} {passed:>6} {deminf_s:>10} {r.final_decision:>10}")

    # --- Cleanup: remove cached .npz files now that scoring is done ---
    removed = 0
    for npz in DEMINF_DATA.rglob("*_cached.npz"):
        npz.unlink()
        removed += 1
    if removed:
        print(f"\n  Cleaned up {removed} cached .npz files from {DEMINF_DATA}")


if __name__ == "__main__":
    main()
